#!/bin/sh

# Specify the full path to the Java bin directory, e.g. JAVA_PATH="/usr/java/jre1.6.0/bin/"
JAVA_PATH=""

PATH=$JAVA_PATH:$PATH
cd `dirname "$0"`
java -Xmx512m -showversion -jar dbedit.jar
if [ $? -ne 0 ]; then
  echo DBEdit requires Java 6
  echo http://java.com/download/
  echo Edit the dbedit script to set JAVA_PATH if you want to use a JRE that is not set in the PATH
fi
